/**
 * Regenerates src/assets.ts from whatever is actually in public/assets.
 *
 * Run it after dropping new files in. Anything missing keeps rendering as a
 * labelled placeholder, so the choreography stays previewable while the art
 * is still being made.
 */
import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const assetDir = join(root, "public", "assets");

const files = readdirSync(assetDir)
  .filter((f) => !f.startsWith("."))
  .sort();

const body = `// GENERATED by \`npm run sync-assets\`. Do not edit by hand.
//
// Anything not listed here renders as a labelled placeholder plate instead of
// an image, so scenes stay previewable before the art exists.

export const PRESENT_ASSETS: ReadonlySet<string> = new Set([
${files.map((f) => `  ${JSON.stringify(f)},`).join("\n")}
]);

export const hasAsset = (filename: string): boolean =>
  PRESENT_ASSETS.has(filename);
`;

writeFileSync(join(root, "src", "assets.ts"), body);
console.log(`sync-assets: ${files.length} asset(s) in public/assets`);
for (const f of files) console.log(`  · ${f}`);
