// GENERATED by `npm run sync-assets`. Do not edit by hand.
//
// Anything not listed here renders as a labelled placeholder plate instead of
// an image, so scenes stay previewable before the art exists.

export const PRESENT_ASSETS: ReadonlySet<string> = new Set([
  "gold-frame.png",
  "grain.jpg",
  "grunge.jpg",
  "wall.jpg",
  "wood-desk.jpg",
]);

export const hasAsset = (filename: string): boolean =>
  PRESENT_ASSETS.has(filename);
